version: '3.2'

services:

#================================================================================================
# WORKSPACE PHP-FPM
#================================================================================================
  workspace-phpfpm:
    restart: always
    build:
      context: .
    ports:
      - "8115:80"
      - "8116:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf                       # config path
      - ./config/php/php.ini:/usr/local/etc/php/php.ini                             # ini path
      - ./config/php/laradock-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini    # xdebug config
      - ./log/phpfpm:/var/log/phpfpm                                                # log phpfpm
      - ./vendor/composer.phar:/usr/local/bin/composer                              # vendor composer
      - ./vendor/deployer.phar:/usr/local/bin/dep                                   # vendor deployer
      - ./vendor/php-cs-fixer:/usr/local/bin/php-cs-fixer                           # vendor php-cs-fixer
      - ./data/laradock:/var/www/html                                               # volume for data
    environment:
      - ALPINE_VERSION=3.7
      - PHP_VERSION=7.2.5
      - XDEBUG_VERSION=2.6.0
      - DEBUG=1
      - NODE_VERSION=10.0.0
      - YARN_VERSION=1.6.0